import React, { useState } from 'react';
import MainLayout from "../../Layout/MainLayout";

function DataPrivacy(){
    return(
        <MainLayout>
            <div className="settingsPagePadding">
                <title>Data Privacy</title>
                <br/>
                <p>
                    Our top priority is the safety and privacy of our customers. As a team, we decided users have full
                    control over their data. Therefore, users have the right to delete their posts and comments, as well
                    as control the data that is displayed about them.
                </p>
                <br/>
                <br/>
                <h1>Privacy Policy</h1>
                <br/>
                <p>
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of
                    Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                    collection and use of information in accordance with this Privacy Policy. This Privacy Policy has
                    been created with the help of the Privacy Policy Generator.
                </p>
                <br/>
                <br/>
                <title>Interpretations and Definitions</title>
                <br/>
                <h1>Interpretation</h1>
                <br/>
                <p>
                    The words of which the initial letter is capitalized have meanings defined under the following
                    conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                <br/>
                <h2>Definitions</h2>
                <br/>
                <p>
                    For the purposes of this Privacy Policy
                </p>
                <br/>
                <li><b>Account</b> means a unique account created for oyu to access our service or parts of our service</li>
                <br/>
                <li>
                    <b>Cookies</b> are small files that are placed on your computer, mobile device or any other device
                    by a website, containing the details of your browsing history on that website among its many uses.
                </li>
                <br/>
                <li>
                    <b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                </li>
                <br/>
                <li>
                    <b>Personal Data</b> is any information that relates to an identified or identifiable individual.
                </li>
                <br/>
                <li>
                    <b>Service</b> refers to the website.
                </li>
                <br/>
                <li>
                    <b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company.
                    It refers to third-party companies or individuals employed by the Company to facilitate the Service,
                    to provide the Service on behalf of the Company, to perform services related to the Service or to
                    assist the Company in analyzing how the Service is used.
                </li>
                <br/>
                <li>
                    <b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service
                    or from the Service infrastructure itself (for example, the duration of a page visit).
                </li>
                <br/>
                <li>
                    <b>Website</b> refers to Outfit Of the Day, accessible from [insert site here]
                </li>
                <br/>
                <li>
                    <b>You</b> means the individual accessing or using the service, or the company, or other legal entity
                    on behalf of which such individual is accessing or using the Service, as applicable.
                </li>
                <br/>
                <br/>
                <title>Collecting and Using Your Personal Data</title>
                <br/>
                <h1>Types of Data Collected</h1>
                <br/>
                <h2>Personal Data</h2>
                <br/>
                <p>
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information
                    that can be used to contact or identify You. Personally identifiable information may include, but is
                    not limited to:
                </p>
                <br/>
                <li>Email Address</li><br/>
                <li>First and Last Name</li><br/>
                <li>Phone Number</li><br/>
                <li>Usage Data</li><br/>
                <h2>Usage Data</h2>
                <br/>
                <p>Usage Data is collected automatically using the service</p>
                <br/>
                <p>
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <br/>
                <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                <br/>
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                <br/>
                <br/>
                <h2>Tracking Technologies and Cookies</h2>
                <br/>
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <li>
                    <b>Cookies or Browser Cookies -</b> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                </li>
                <br/>
                <li>
                    <b>Web Beacons - </b> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                </li>
                <br/>
                <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Privacy Policies website article.</p>
                <br/>
                <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                <li>
                    <b>Necessary / Essential Cookies</b> <br/>
                    Type: Session Cookies<br/>
                    Administered by: Us <br/>
                    Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                </li>
                <br/>
                <li>
                    <b>Cookies Policy / Notice Acceptance Cookies</b><br/>
                    Type: Persistent Cookies<br/>
                    Administered by: Us <br/>
                    Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                </li>
                <br/>
                <li>
                    <b>Functionality Cookies</b> <br/>
                    Type: Persistent Cookies<br/>
                    Administered by: Us <br/>
                    Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                </li>
                <br/>
                <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                <br/>
                <br/>
                <h2>Use of Your Personal Data</h2>
                <br/>
                <p>The company may use personal data for the following purposes: </p>
                <br/>
                <li>
                    <b>To provide and maintain our Service</b>, including to monitor the usage of our Service.
                </li>
                <br/>
                <li>
                    <b>To manage Your Account: </b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                </li>
                <br/>
                <li>
                    <b>For the performance of a contract: </b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                </li>
                <br/>
                <li>
                    <b>To contact You: </b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                </li>
                <br/>
                <li>
                    <b>To Provide You: </b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                </li>
                <br/>
                <br/>
                <title>Transfer of Your Personal Data</title>
                <br/>
                <p>
                    Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.<br/>
                    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.<br/>
                    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                </p>
                <title>Delete your personal Data</title>
                <br/>
                <p>
                    You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.<br/>
                    Our Service may give You the ability to delete certain information about You from within the Service.<br/>
                    You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.<br/>
                    Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
                </p>
                <br/>
                <br/>
                <title>Disclosure Your Personal Data</title>
                <br/>
                <h2>Business Transactions</h2>
                <br/>
                <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                <br/>
                <br/>
                <h2>Law Enforcement</h2>
                <br/>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                <br/>
                <br/>
                <h2>Other legal requirements</h2>
                <br/>
                <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <br/>
                <li>Comply with a legal obligation</li>
                <br/>
                <li>Protect and defend the rights or property of the Company</li>
                <br/>
                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                <br/>
                <li>Protect the personal safety of Users of the Service or the public</li>
                <br/>
                <li>Protect against legal liability</li>
                <br/>
                <br/>
                <title>Security of your personal Data</title>
                <br/>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                <br/>
                <br/>
                <title>Children's Privacy</title>
                <br/>
                <p>
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. <br/>
                    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
                </p>
                <br/>
                <br/>
                <title>Links to Other Websites</title>
                <br/>
                <p>
                    Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.<br/>
                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
                <br/>
                <br/>
                <title>Changes to this privacy policy</title>
                <br/>
                <p>
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. <br/>
                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. <br/>
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
                <br/>
                <br/>
                <title>Contact Us</title>
                <br/>
                <p>If you have any questions about this Privacy Policy, you can find our contact information on the about us page located at the bottom of your screen.</p>

            </div>
        </MainLayout>
    );
}
export default DataPrivacy;